apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tailscale-svc-lb-controller
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tailscale-svc-lb-controller
subjects:
  - kind: ServiceAccount
    name: {{ include "tailscale-svc-lb.serviceAccountName" . }}
    namespace: "{{ .Release.Namespace }}"
roleRef:
  kind: ClusterRole
  name: tailscale-svc-lb-controller
  apiGroup: rbac.authorization.k8s.io