{{- if .Values.tailscaleAuthKey }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: "tailscale-svc-lb"
  labels:
    {{- include "tailscale-svc-lb.labels" . | nindent 4 }}
stringData:
  ts-auth-key: "{{ .Values.tailscaleAuthKey }}"
{{- end }}
