apiVersion: v1
kind: Service
metadata:
  name: kuard
spec:
  selector:
    run: kuard
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  loadBalancerClass: "svc-lb.tailscale.iptables.sh/lb"