name: Build and publish Docker image

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push controller image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: clrxbl/tailscale-svc-lb-controller:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Build and push runtime image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: clrxbl/tailscale-svc-lb-runtime:latest
          context: "{{defaultContext}}:runtime"
          cache-from: type=gha
          cache-to: type=gha,mode=max